image: golang:1.11

before_script:
  - apt-get update -y -qq
  - apt-get install -y sqlite3 libsqlite3-dev
  - mkdir -p $GOPATH/src/github.com/ziotom78/
  - ln -s /builds/tomasi/qutedb $GOPATH/src/github.com/ziotom78/
  - cd $GOPATH/src/github.com/ziotom78/qutedb
  
cache:
  paths:
    - /apt-cache
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - deploy

deploy:
  stage: deploy
  script:
    - pwd
    - go env
    - go get -v github.com/spf13/viper
    - go get -v github.com/elithrar/simple-scrypt
    - go get -v github.com/gobuffalo/uuid
    - go get -v github.com/gorilla/mux
    - go get -v github.com/gorilla/securecookie
    - go get -v github.com/jinzhu/gorm
    - go get -v github.com/mattn/go-sqlite3
    - go get -v github.com/sirupsen/logrus
    - go get -v github.com/astrogo/fitsio
    - go install -v ./...
    - go test -race
    - createqdbcfg --staticpath /go/src/github.com/ziotom78/qutedb/static --repositorypath /repository --port 8080 | tee config.json
    - qutedb
