image: ziotom78/qutedb

cache:
  paths:
    - /apt-cache
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - build
  - test
  - staging
  - production

install:
  stage: build
  script:
    - go get -v github.com/ziotom78/qutedb

deps:
  stage: build
  script:
    - go install -v ./...

runtests:
  stage: test
  script:
    - go test -race

staging:
  stage: staging
  script: # Todo: make /repository point to some meaningful location
    - createdqbcfg --staticpath /go/src/github.com/ziotom78/qutedb/static --repositorypath /repository --port 8080 | tee config.json

run:
  stage: production
  script:
    - qutedb

