image: golang:1.11

before_script:
  - apt-get update -y -qq
  - mkdir -p $GOPATH/src/github.com/ziotom78/
  - ln -s /builds/tomasi/qutedb $GOPATH/src/github.com/ziotom78/
  - cd $GOPATH/src/github.com/ziotom78/qutedb
  
cache:
  paths:
    - /apt-cache
    - /go/src/golang.org
    - /go/src/google.golang.org
    - /go/src/gopkg.in

stages:
  - build
  - production

build:
  stage: build
  script:
    - pwd
    - go env
    - ls -l $GOPATH/src/github.com/ziotom78/qutedb/*
    - ls -l /builds/tomasi/qutedb
    - go install -v ./...
    - go test -race
    - createdqbcfg --staticpath /go/src/github.com/ziotom78/qutedb/static --repositorypath /repository --port 8080 | tee config.json

deploy:
  stage: production
  script:
    - qutedb

